### ISSUE TITLE
Add Support For Custom Sphinx extensions and themes

### ISSUE THREAD

**Issue by menckend** [Kjuly/sphinx-builder#1]
### Describe the problem you'd like to have solved

I'd like to use Sphinx-publisher to publish my documentation to GitHub-pages, but it seems as though the docker image that the action is using to invoke sphinx doesn't have the items from ...docs/requirements.txt installed and my builds fail with Spinx erros complaining about missing modules (for 3rd party extensions, such as "sphinx_autodoc_typehints") or themes (such as "sphinx_rtd_theme).

### Describe the ideal solution

Accept the contents of "...docs/requirements.txt" from the client invoking the action; push them into the tail-end of a "pip install...." command in the Dockerfile used to invoke the docker image that Sphinx runs on.

### Alternatives and current workarounds

Nothing comes to mind.

**Comment by Kjuly** [comment]
Hi there, I've updated the repo to handle the `requirements.txt` file if it exists under the same dir of `_conf.py`.

You can refer to the example in the ["Share & Override Config File"](https://github.com/Kjuly/sphinx-builder?tab=readme-ov-file#share--override-config-file) section.

Hope it helps. ;)

**Comment by menckend** [comment]
Thanks so much; worked like a charm!
